version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - learning-lab-net

networks:
  learning-lab-net:
    external: true
